version: '3.8'

services:
    mongodb:
        networks:
            - ring
        ports:
            - 27017:27017
        image: mongo:latest
        volumes:
            - mongodb-data:/data/db
            - ./mongodb/mongod.conf:/etc/mongod.conf

networks:
    ring:

volumes:
    mongodb-data: