version: '3.8'

services:
    mongodb:
        hostname: database.servicetws.com
        networks:
            - ring
        ports:
            - 27017:27017
        image: mongo:latest
        volumes:
            - mongodb-data:/data/db
            - ./mongodb/mongo:/etc/mongo
            - ./mongodb/ssl:/etc/ssl
            - ./mongodb/log:/var/log/mongodb
        entrypoint: ["mongod"]
        command: ["--config","/etc/mongo/mongod.conf"]
        user: 1000:1000
    session:
        hostname: session.servicetws.com
        networks:
          - ring
        ports:
          - 6379:6379
        image: redis:latest
        volumes:
          - ./session/config/redis.conf:/usr/local/etc/redis/redis.conf
          - ./session/ssl:/usr/local/etc/ssl
        command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    backend:
        hostname: backend.servicetws.com
        networks:
            - ring
        build:
            context: ./backend
            args:
                node_env: development
        depends_on:
            - mongodb
    frontend:
        hostname: frontend.servicetws.com
        networks:
            - ring
        build:
            context: ./frontend
        volumes:
            - ./frontend/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./frontend/ssl:/etc/ssl/certs
            - ./frontend/includes/mime.types /etc/nginx/includes/mime.types
            - ./frontend/includes/proxy.conf /etc/nginx/includes/proxy.conf
        depends_on:
            - backend

    reverse:
        hostname: reverse.servicetws.com
        networks:
            - ring
        ports:
            - 80:80
            - 443:443
        image: nginx:latest
        volumes:
            - ./reverse/conf/nginx.conf:/etc/nginx/nginx.conf
            - ./reverse/ssl:/etc/ssl/certs
            - ./reverse/includes/mime.types /etc/nginx/includes/mime.types
            - ./reverse/includes/proxy.conf /etc/nginx/includes/proxy.conf
        depends_on:
            - backend
            - frontend

networks:
    ring:

volumes:
    mongodb-data: